use gz-physics#283 to implement joint_states/effort feedback
ros-controls/gz_ros2_control pull request #186
Opened 2023-10-07 15:04 UTC by andreasBihlmaier

Fixes `joint_states/effort` being zero for joints with `<state_interface name="effort" />` in combination with `joint_state_broadcaster/JointStateBroadcaster` by using the `JointTransmittedWrench` component introduced by gz-physics#283.

The joint axis is hard coded to `z`. I did not yet look into reading out the actual `<axis>` of the joint and extracting the respective force/torque component of the wrench.

2023-10-09 10:10 UTC, ahcorde requested changes
Thank you for the contribution. 
Two comments:

 - Can you review linters? 
 - can you add a comment related to the hardcoded `z` joint ? or do you plan to continue working on this PR ?

2023-10-11 03:05 UTC, Nemantor commented
I tried it and it works properly, couldn't find any problems

2024-06-13 15:33 UTC, BarisYazici commented
We are currently integrating Gazebo and would like to have the efforts from simulation. How is this PR going?

2024-06-14 15:20 UTC, andreasBihlmaier commented
I'll take a quick look this weekend whether I can get this PR cleaned up and submitted.

2024-06-14 17:52 UTC, andreasBihlmaier commented
This should do it (further testing strongly recommended): https://github.com/andreasBihlmaier/gz_ros2_control/commit/59ef8f0170c3dfaa3b8135ca524113731ce8821e

I'll try to either update this PR or create a new one in the next days.

2024-06-16 20:20 UTC, andreasBihlmaier commented
I did a bit of quick testing wrsp to joint axis. The effort seems to be reported as expected.
I force pushed https://github.com/andreasBihlmaier/gz_ros2_control/tree/fix-effort-state-jazzy onto the fix-effort-state branch (GitHub does not allow to change PR source branches) and retargeted this PR to jazzy branch.

2024-06-20 11:48 UTC, BarisYazici commented
I tested this. It works for us. Thanks a lot @andreasBihlmaier

2024-10-02 16:54 UTC, azeey commented
@ahcorde this looks good to me. Any reason for not merging?

2024-10-28 08:59 UTC, ahcorde approved these changes

2024-10-28 09:00 UTC, merged

2024-10-28 09:01 UTC, ahcorde commented
https://github.com/Mergifyio backport rolling humble iron

2025-05-23 14:04 UTC, federicociresola commented
Hi guys,
I noticed that the backporting for Humble didn't work because the file modified in this PR there are not in the Humble branch https://github.com/ros-controls/gz_ros2_control/blob/humble/gz_ros2_control/src/gz_system.cpp
- PR Backporting filed: https://github.com/ros-controls/gz_ros2_control/pull/431

I have implemented the changes in this PR in my forked Humble branch and it works fine

2025-06-10 20:44 UTC, christophfroehlich commented
@mergifyio backport humble