Rename cartpole with cart
ros-controls/gz_ros2_control pull request #214
Opened 2024-01-03 10:53 UTC by ahcorde

Related with this PR in `gazebo_ros2_control` https://github.com/ros-controls/gazebo_ros2_control/pull/252

2024-01-03 11:19 UTC, christophfroehlich requested changes
The changes here are missing (still referring to a cart-pole controller): https://github.com/ros-controls/gazebo_ros2_control/pull/252/files#diff-3161f66a61b9ed68303607f1dbdce1c7bdcc69c42f8ea1c2051a07a579ebcf5dR210-R217

2024-01-03 11:19 UTC, christophfroehlich commented on gz_ros2_control_demos/launch/tricycle_drive_example.launch.py
> +                   '-name', 'cart',
```suggestion
                   '-name', 'tricycle',
```

2024-01-03 12:09 UTC, christophfroehlich requested changes
Sorry, but this is still not a valid ros2_control yaml (there is no `type` or `write_op_modes` parameter). Instead of the two code-blocks in L212,220, you could just use
```
.. literalinclude:: ../gz_ros2_control_demos/config/cart_controller_position.yaml
   :language: yaml
```

2024-01-03 12:11 UTC, christophfroehlich commented
Btw the "Check Docs" CI job fails because of another issue with control.ros.org

2024-01-03 12:37 UTC, ahcorde commented
@christophfroehlich  not really sure about how to solve this issue

```bash
 /home/runner/work/gz_ros2_control/gz_ros2_control/doc/acknowledgements/acknowledgements.rst:70: CRITICAL: Problems with "raw" directive path:
InputError: [Errno 2] No such file or directory: 'doc/acknowledgements/reviewers_stats.html'.
```

2024-01-03 12:43 UTC, christophfroehlich approved these changes

2024-01-03 12:44 UTC, christophfroehlich commented
> @christophfroehlich not really sure about how to solve this issue
> 
> ```shell
>  /home/runner/work/gz_ros2_control/gz_ros2_control/doc/acknowledgements/acknowledgements.rst:70: CRITICAL: Problems with "raw" directive path:
> InputError: [Errno 2] No such file or directory: 'doc/acknowledgements/reviewers_stats.html'.
> ```

As I said, a bug on control.ros.org -> I fixed it in the meantime.

2024-01-03 12:48 UTC, ahcorde commented
thank you @christophfroehlich for pushing gazebo_ros2_control and gz_ros2_control

2024-01-03 12:55 UTC, merged

2024-01-04 09:59 UTC, ahcorde commented
https://github.com/Mergifyio backport humble iron