New branch and fix API breaking to allow Humble to work with Gazebo Garden
ros-controls/gz_ros2_control pull request #268
Opened 2024-04-02 12:46 UTC by federicociresola

Hi guys,
I created this PR to allow Humble to work with Gazebo Garden. 
I started to work with iron branch because it contains the porting from ignition to gazebo API. I discovered that the ros2_control repository has changed the API from Humble to Iron. Therefore, I updated the code with old version of ros2_control's API. 

It seems to work without problem with Humble and Garden. My idea is to keep a two different branches, so a person can choose if need to work with Gazebo Garden or Ignition Fortress.

Tell me what do you think about this idea

2024-04-02 13:10 UTC, ahcorde requested changes
as you can see there are many files with changes, I can't review this PR. Can you open cleaner PR or edit this PR to contain only the changes that you want to contribute?

2024-04-02 13:28 UTC, federicociresola commented
sorry, I just noticed that I made a mistake on the branch. My idea is not merge this code in the branch `iron` but keep them in two difference branches. Tell me if it is possible

2024-04-09 16:10 UTC, destogl commented
@federicociresola as we will not be able to relese this. It doesn't make much sense to merge this as you will anyway need to build everything from source, you can also work from your fork.

2024-04-10 07:10 UTC, federicociresola commented
@destogl My idea is not merge it on main branch but create a separate branch (I don't know if it is possible because I am quite new in this world to contribute on public repository). I'm asking this because I am updating the code of create3 to work with Humble and Gazebo Garden (the idea is to make a PR for that project when I will finish) and it needs this patch. 
Therefore I thought that it was good for the community if they can use it from official repository also if they have to clone the repository and compile it

2025-01-21 21:17 UTC, christophfroehlich commented
Closing this as [Garden has reached its EOL](https://community.gazebosim.org/t/gazebo-garden-officially-end-of-life/3278)

2025-01-21 21:17 UTC, closed without merging