Add code for supporting mimic joints.
ros-controls/gz_ros2_control pull request #33
Opened 2022-02-05 23:34 UTC by destogl

This PR adds the same support for mimic joints as in ﻿ros-simulation/gazebo_ros2_control#107.

The code is just sligtly adjusted to work with Ignition.

@ahcorde: I have a question regarding writing postion commands to the simulator from the plugin. It is a bit different then for velocity and effort. Is this wrong?

Also I have an compilation issue with this code, but there is no error output about it. Do you have any idea?

2022-02-08 10:24 UTC, ahcorde requested changes

2022-02-10 10:54 UTC, ahcorde commented
Ey @destogl,

I want to get rid of `JointPositionReset`, this is not the right way to use this ignition::gazebo::component. I would like to use this solution https://github.com/ignitionrobotics/ign_ros2_control/pull/29

2022-02-11 13:52 UTC, destogl commented
> Ey @destogl,
> 
> I want to get rid of `JointPositionReset`, this is not the right way to use this ignition::gazebo::component. I would like to use this solution #29

Thanks! I will rebase this to the feature branch and update my code accordingly in the next few days.

2022-03-16 11:45 UTC, ahcorde commented
friendly ping @destogl

2022-03-16 19:11 UTC, destogl commented
Sorry, didn't manage to go back to it. Do you have any bandwidth to finish this. I will need few more days until I manage to come to it.

2022-03-17 08:50 UTC, ahcorde commented
No worries, it was just a reminder

2022-04-14 10:57 UTC, livanov93 commented
@ahcorde Friendly ping for a review.

2022-04-15 06:23 UTC, destogl commented on ign_ros2_control/src/ign_system.cpp
> +
```suggestion
```

2022-04-15 11:41 UTC, livanov93 commented on ign_ros2_control/src/ign_system.cpp
> +
[bb465b3](https://github.com/ignitionrobotics/ign_ros2_control/pull/33/commits/bb465b394b0be207bd5fd6a5a07e0922668e13af)

2022-08-15 09:16 UTC, ahcorde requested changes
@destogl conflicts

2022-08-25 18:09 UTC, livanov93 commented
@destogl please change base branch to `master`

2022-08-26 10:46 UTC, ahcorde requested changes
there are some linter errors

can you merge the PR with `master`?

2022-09-01 16:54 UTC, ahcorde approved these changes

2022-09-01 16:54 UTC, merged