Add Demos for SDF
ros-controls/gz_ros2_control pull request #427
Opened 2024-10-17 16:15 UTC by Amronos

Adds demos for SDF. Linked to [#ros2_control/1763](https://github.com/ros-controls/ros2_control/pull/1763).
These demos should help in testing the PR.

A couple of things I want an opinion on:
1. Should using URDF or SDF be an argument of the launch file?
2. What should be the name of the launch file?
3. I have put the SDF files in a new `sdf` directory is that okay or should something else be done?

2024-11-08 12:16 UTC, Amronos commented
@ahcorde Can I get an initial review?

2024-11-08 14:42 UTC, ahcorde requested changes

2024-11-08 14:42 UTC, ahcorde commented on gz_ros2_control_demos/launch/diff_drive_example_sdf.launch.py
> +# Copyright 2022 Open Source Robotics Foundation, Inc.
```suggestion
# Copyright 2024 Open Source Robotics Foundation, Inc.
```

2024-11-08 14:42 UTC, ahcorde commented on gz_ros2_control_demos/launch/diff_drive_example_sdf.launch.py
> +    )
you don't need to do that, the sdf file doesn't have any xacro tag. You should read the file as it's

2024-11-08 14:44 UTC, ahcorde commented on gz_ros2_control_demos/launch/diff_drive_example_sdf.launch.py
> +    )
you should be able to use something like `from launch.substitutions import FileContent`

2024-11-30 09:23 UTC, Amronos commented
@ahcorde I decided it would be better for the description format to be an argument of the launch file. I did need to use an OpaqueFunction for this (please tell me if there is a simple way), have a look at ed7f047.
Another option would be not using SDF at all in the launch files and instead just having them be present in the `sdf` directory.

2024-11-30 09:54 UTC, bmagyar commented
If the purpose of the demo is to have a urdf and sdf description separately demonstrated, I think the separate argument makes sense.

2024-12-02 08:34 UTC, ahcorde requested changes
Do you mind to add some docs to the README.md ?

2024-12-02 09:06 UTC, ahcorde requested changes
There are conflicts, do you mind to fix it ?

2024-12-02 11:40 UTC, Amronos commented
If everything looks good now, I will also add SDF versions for the other demos.

2024-12-02 12:40 UTC, ahcorde requested changes
While I was compiling the documentation of this PR I noticed that the setup is wrong. This PR should configure the docs file properly.

also If you run the documentation command there are some errors

2024-12-02 12:40 UTC, ahcorde commented on doc/index.rst
> +URDF:
```suggestion
URDF:

```

2024-12-02 12:40 UTC, ahcorde commented on doc/index.rst
> +  </plugin>
```suggestion
  </gazebo>

SDF:

.. code-block:: xml

  <plugin filename="libgz_ros2_control-system.so" name="gz_ros2_control::GazeboSimROS2ControlPlugin">
    <parameters>$(find gz_ros2_control_demos)/config/cart_controller.yaml</parameters>
  </plugin>
```

2024-12-02 12:40 UTC, ahcorde commented on doc/index.rst
```suggestion
URDF:

.. code-block:: xml

```

2024-12-02 12:40 UTC, ahcorde commented on doc/index.rst
> +.. code-block:: xml
```suggestion
  </gazebo>

SDF:

.. code-block:: xml

```

2024-12-02 12:40 UTC, ahcorde commented on doc/index.rst
>  .. code-block:: xml
```suggestion
URDF:

.. code-block:: xml
```

2024-12-02 12:40 UTC, ahcorde commented on doc/index.rst
> +.. code-block:: xml
```suggestion
  </gazebo>

SDF:

.. code-block:: xml
```

2024-12-02 12:40 UTC, ahcorde commented on doc/index.rst
>  .. code-block:: xml
```suggestion
URDF:

.. code-block:: xml
```

2024-12-02 12:40 UTC, ahcorde commented on doc/index.rst
> +.. code-block:: xml
```suggestion
    <gazebo>

SDF:

.. code-block:: xml
```

2024-12-02 12:40 UTC, ahcorde commented on doc/index.rst
> +  ros2 launch gz_ros2_control_demos ....launch.py description_format:=sdf
```suggestion
  ros2 launch gz_ros2_control_demos <launch file> description_format:=sdf
```

2024-12-02 14:06 UTC, ahcorde requested changes

2024-12-02 14:06 UTC, ahcorde commented on doc/index.rst
> +    <gazebo>
restore this line change

2024-12-03 10:58 UTC, ahcorde requested changes
There are some issues:

```
gz_ros2_control_demos/launch/ackermann_drive_example.launch.py:39:21: E128 continuation line under-indented for visual indent
gz_ros2_control_demos/launch/ackermann_drive_example.launch.py:40:21: E128 continuation line under-indented for visual indent
gz_ros2_control_demos/launch/ackermann_drive_example.launch.py:91:9: E222 multiple spaces after operator
gz_ros2_control_demos/launch/diff_drive_example.launch.py:39:21: E128 continuation line under-indented for visual indent
gz_ros2_control_demos/launch/diff_drive_example.launch.py:40:21: E128 continuation line under-indented for visual indent
```

2024-12-03 11:18 UTC, Amronos commented on doc/index.rst
> +    <gazebo>
Fixed in commit [38b6dc1](https://github.com/ros-controls/gz_ros2_control/pull/427/commits/38b6dc1725a6b883b46e03a3e7cff6ba3c69a3e5).

2024-12-03 12:26 UTC, ahcorde requested changes
is the robot moving ? I can't move the diff_drive or ackermann examples

2024-12-03 13:21 UTC, Amronos commented
> is the robot moving ? I can't move the diff_drive or ackermann examples

Yes, the robot does move for me upon running `ros2 run gz_ros2_control_demos example_diff_drive` for diff_drive or `ros2 run gz_ros2_control_demos example_ackermann_drive` for ackermann.
Make sure you have the [sdformat_urdf](https://index.ros.org/p/sdformat_urdf/github-ros-sdformat_urdf/#rolling) package installed and are using a version of `hardware_interface` that has [this](https://github.com/ros-controls/ros2_control/commit/93a2a68f6ab4110b7e5816bce134437780ba3bf3) commit.

2024-12-04 08:53 UTC, ahcorde approved these changes

2024-12-04 08:53 UTC, ahcorde commented
The issue that I mentioned is unrelated to this PR, we can merge this.

2024-12-04 08:54 UTC, merged

2024-12-23 21:06 UTC, christophfroehlich commented
@mergifyio backport jazzy