Update diff_drive controller parameters
ros-controls/gz_ros2_control pull request #462
Opened 2024-12-23 18:15 UTC by Wiktor-99

PR addresses the #459

2024-12-23 19:38 UTC, bmagyar approved these changes

2024-12-23 19:43 UTC, saikishor approved these changes

2024-12-23 20:17 UTC, ahcorde approved these changes

2024-12-23 20:17 UTC, merged

2024-12-23 20:18 UTC, ahcorde commented
Thank your @Wiktor-99

2024-12-23 20:19 UTC, christophfroehlich requested changes
thanks @Wiktor, but this isn't your first issue in ros-controls, right? 😅

2024-12-23 20:19 UTC, christophfroehlich commented on gz_ros2_control_demos/config/diff_drive_controller.yaml
>      linear.x.has_velocity_limits: true
velocity and acceleration are deprecated similarly (just no output if the value is true, i.e., the default)

2024-12-23 20:48 UTC, christophfroehlich commented
@mergifyio backport jazzy

2024-12-23 21:57 UTC, Wiktor-99 commented
> thanks @wiktor, but this isn't your first issue in ros-controls, right? 😅

You're right. I didn't know that the good first issue policy is so strict.😂
Since I've started, I believe I can fix the rest of the parameters.

2024-12-23 22:04 UTC, christophfroehlich commented
it's not strict. But sometimes it's hard to find easy tasks to help onboarding of new contributers. If experienced developers also take these tasks although not urgent, then nothing is left for them 🫣

2024-12-24 10:14 UTC, Wiktor-99 commented
Gotcha, next time I'll try to pick more complicated issues